version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - echo Build started on `date`
      
  post_build:
    commands:
      - aws s3 sync . s3://${WebsiteBucket}/