AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront distribution with S3 bucket
  
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
  S3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref S3Bucket
        PolicyDocument:
          Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${S3Bucket}/*
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId

  CFDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: workshop website distribution
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 404
            ResponsePagePath: /index.html
            ResponseCode: 200
          - ErrorCode: 403
            ResponsePagePath: /index.html
            ResponseCode: 200 
        Origins:
          - DomainName: !Sub ${S3Bucket}.s3.amazonaws.com
            Id: workshop-s3-bucket
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: workshop-s3-bucket
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_100
        HttpVersion: http2

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: CloudFront OAI for Secured S3 Static Website

Outputs:
  S3Bucket:
    Description: Bucket with content to be displayed on the website. Default file should be index.html
    Value: !Ref S3Bucket
  CFDistribution:
    Description: Cloudfrondistribution
    Value: !Ref CFDistribution